# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92374488c1a35887b9e370d2f5d91c4a8c39db9c7671e4c96cbd929883e80ecc2a1a68394872a918f2b669b06dc3301a4f72716af6482cffea794f310b18df92

test:
  secret_key_base: 3bb3cb5f5c94bd864ad2590514a8a4f3d57bc2b5822a7418d66dad56708c6ee27ced6f6ee5750a59258ef02b019f45f49b6e96a03f6725dc80e031493bb380b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
